### ISSUE TITLE
Aggiornare struttura directory GitHub

### ISSUE THREAD

**Issue by giodabg** [Dev-Doctor/CharacterGenerator#6]
La struttura tipo del repository dovrebbe essere simile a questa (versione minimale):
file Readme.md
cartella codice/code/project/htdocs/...
cartella documentazione

**Comment by Dev-Doctor** [comment]
C'è un branch apposito per la documentazione -> [documentation](/Dev-Doctor/CharacterGenerator/tree/documentation)
